language: java
jdk:
  - oraclejdk8

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t a14c0ffe-c15f-4fc9-a314-9c50a3b8627b

before_install:
  - npm i -g npm@latest
  - npm i -g @angular/cli@8.0.3
  - chmod +x mvnw
