insert into ACCOUNT(ID, NAME, BALANCE) values ( 1, 'Ned Stark'          ,    7470.49);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 2, 'Robert Baratheon'   ,    6517.38);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 3, 'Jaime Lannister'    ,    8543.12);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 4, 'Catelyn Stark'      ,     270.32);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 5, 'Cersei Lannister'   ,   11603.46);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 6, 'Daenerys Targaryen' ,    3358.40);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 7, 'Jorah Mormont'      ,  100000.00);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 8, 'Viserys Targaryen'  ,    3343.17);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 9, 'Jon Snow'           ,    5688.11);
insert into ACCOUNT(ID, NAME, BALANCE) values (10, 'Sansa Stark'        ,    4418.91);
insert into ACCOUNT(ID, NAME, BALANCE) values (11, 'Arya Stark'         ,      10.66);
insert into ACCOUNT(ID, NAME, BALANCE) values (12, 'Robb Stark'         ,    4743.62);
insert into ACCOUNT(ID, NAME, BALANCE) values (13, 'Theon Greyjoy'      ,  902879.90);
insert into ACCOUNT(ID, NAME, BALANCE) values (14, 'Bran Stark'         ,    5923.34);
insert into ACCOUNT(ID, NAME, BALANCE) values (15, 'Joffrey Baratheon'  ,    4424.23);
insert into ACCOUNT(ID, NAME, BALANCE) values (16, 'Sandor Clegane'     ,       0.00);
insert into ACCOUNT(ID, NAME, BALANCE) values (17, 'Tyrion Lannister'   ,    8713.19);
insert into ACCOUNT(ID, NAME, BALANCE) values (18, 'Khal Drogo'         ,     731.00);


insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 1, 17, 1, 333.46);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 2, 1, 12, 1000.00);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 3, 2, 13, 333.46);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 4, 1, 13, 1000.00);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 5, 3, 15, 1333.46);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 6, 1, 14, 1000.00);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 7, 2, 1, 1.46);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 8, 1, 15, 1000.00);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 9, 1, 14, 333.46);
insert into TRANSFER(ID, SOURCE_ID, TARGET_ID, AMOUNT) values ( 10, 1, 11, 1.99);