insert into ACCOUNT(ID, NAME, BALANCE) values ( 1, 'Hulk',                  7470.49);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 2, 'Rocket Raccoon',        6517.38);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 3, 'Star-Lord',             8543.12);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 4, 'Quicksilver',            270.32);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 5, 'Thor',                 11603.46);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 6, 'Wasp',                  3358.40);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 7, 'Gambit',              222173.78);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 8, 'She-Hulk',              3343.17);
insert into ACCOUNT(ID, NAME, BALANCE) values ( 9, 'Daredevil',             5688.11);
insert into ACCOUNT(ID, NAME, BALANCE) values (10, 'Drax the Destroyer',    4418.91);
insert into ACCOUNT(ID, NAME, BALANCE) values (11, 'Clint Barton',          1518.71);
insert into ACCOUNT(ID, NAME, BALANCE) values (12, 'Groot',                 4743.62);
insert into ACCOUNT(ID, NAME, BALANCE) values (13, 'Loki',                902879.90);
insert into ACCOUNT(ID, NAME, BALANCE) values (14, 'Jessica Jones',         5923.34);
insert into ACCOUNT(ID, NAME, BALANCE) values (15, 'Wanda Maximoff',        4424.23);
insert into ACCOUNT(ID, NAME, BALANCE) values (16, 'Captain America',      21030.00);
insert into ACCOUNT(ID, NAME, BALANCE) values (17, 'War Machine',           8713.19);
insert into ACCOUNT(ID, NAME, BALANCE) values (18, 'Beast',                  731.00);
insert into ACCOUNT(ID, NAME, BALANCE) values (19, 'X-23',                  1151.96);
insert into ACCOUNT(ID, NAME, BALANCE) values (20, 'Spider-Man',            6193.46);